# Generated by Django 5.1.2 on 2024-11-05 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choco_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersuggestions',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='suggestions', to='choco_app.ingredients'),
        ),
    ]
